<template>
    <VCard class="ma-5 d-flex flex-column justify-center align-center">
        <VAvatar image="@/assets/avei.jpg" size="80" class="" />
        <VCardTitle color="primary" class="text-center font-bold"
            >I am Avei</VCardTitle
        >
        <VCardItem class="">
            <VBtn
                class="mx-1"
                icon="mdi-github"
                density="compact"
                href="https://github.com/Avei20"
            />
            <VBtn
                class="mx-1"
                icon="mdi-linkedin"
                density="compact"
                href="https://www.linkedin.com/in/avei"
            />
            <VBtn
                class="mx-1"
                icon="mdi-twitter"
                density="compact"
                href="https://twitter.com/avei__"
            />
            <VBtn
                class="mx-1"
                icon="mdi-instagram"
                density="compact"
                href="https://instagram.com/avei___"
            />
        </VCardItem>
        <VCardText class="text-center py-2">
            Here are a list of my production work which can be accessed by in my
            Github account. Feel free to contact me for collaboration about AI,
            Machine Learning and Web Development Projects.
        </VCardText>
        <VCardItem class="w-100">
            <VDivider />
            <VExpansionPanels>
                <VExpansionPanel
                    class="ma-2"
                    title="Gemini Chat"
                    color="primary"
                >
                    <VExpansionPanelText>
                        <span
                            >Self-made AI chatbot using Gemini API with
                            websocket connection into
                            <a href="https://nest.avei.ovh/docs"
                                >Avei Nest.js</a
                            >
                            backend</span
                        >
                        <div
                            class="d-flex align-center justify-item-between pt-3"
                        >
                            <VBtn
                                class="w-fit mx-3"
                                icon="mdi-github"
                                density="compact"
                                href="https://github.com/Avei20/avei-nuxt"
                            />
                            <VBtn class="w-fit mx-3" color="primary" to="/chat">
                                Try It!</VBtn
                            >
                        </div>
                    </VExpansionPanelText>
                </VExpansionPanel>
                <VExpansionPanel
                    class="ma-2"
                    title="Knowledge Graph"
                    color="primary"
                >
                    <VExpansionPanelText>
                        <span>
                            Knowledge Graph is a graph database using neo4j. The
                            graph is generated by injecting LLM response into
                            the database and visualize using sigma.js.
                        </span>
                        <div
                            class="d-flex align-center justify-item-between pt-3"
                        >
                            <VBtn
                                class="w-fit mx-3"
                                icon="mdi-github"
                                density="compact"
                                href="https://github.com/Avei20/avei-nuxt"
                            />
                            <VBtn
                                class="w-fit mx-3"
                                color="primary"
                                to="/graph"
                            >
                                Try it!
                            </VBtn>
                        </div>
                    </VExpansionPanelText>
                </VExpansionPanel>
                <VExpansionPanel
                    class="ma-2"
                    title="Selfhosted Excalidraw"
                    color="primary"
                >
                    <VExpansionPanelText>
                        <span>
                            Excalidraw is a whiteboard tool that let you draw
                            and collaborate with your team. This is a selfhosted
                            version of Excalidraw.
                        </span>
                        <div
                            class="d-flex align-center justify-item-between pt-3"
                        >
                            <VBtn
                                class="w-fit mx-3"
                                icon="mdi-github"
                                density="compact"
                                href="httpe://github.com/Avei20/avei-draw"
                            />
                            <VBtn
                                class="w-fit mx-3"
                                color="primary"
                                href="https://draw.avei.ovh"
                            >
                                Try it!
                            </VBtn>
                        </div>
                    </VExpansionPanelText>
                </VExpansionPanel>
                <VExpansionPanel
                    class="ma-2"
                    title="Nest.js API"
                    color="primary"
                >
                    <VExpansionPanelText>
                        <span>
                            Nest.js API is a backend API for my production work.
                            It is a REST API with Swagger Docs.
                        </span>
                        <div
                            class="d-flex align-center justify-item-between pt-3"
                        >
                            <VBtn
                                class="w-fit mx-3"
                                icon="mdi-github"
                                density="compact"
                                href="https://github.com/Avei20/avei-nest"
                            />
                            <VBtn
                                class="w-fit mx-3"
                                color="primary"
                                href="https://nest.avei.ovh/docs"
                            >
                                Try it!
                            </VBtn>
                        </div>
                    </VExpansionPanelText>
                </VExpansionPanel>
                <VExpansionPanel class="ma-2" title="Echo API" color="primary">
                    <VExpansionPanelText>
                        <span>
                            Echo API is a backend API for my production work. It
                            is a REST API with Swagger Docs.
                        </span>
                        <div
                            class="d-flex align-center justify-item-between pt-3"
                        >
                            <VBtn
                                class="w-fit mx-3"
                                icon="mdi-github"
                                density="compact"
                                href="https://github.com/Avei20/avei-echo"
                            />
                            <VBtn
                                class="w-fit mx-3"
                                color="primary"
                                href="https://echo.avei.ovh/"
                            >
                                Try it!
                            </VBtn>
                        </div>
                    </VExpansionPanelText>
                </VExpansionPanel>
                <VExpansionPanel
                    class="ma-2"
                    title="Elysia API"
                    color="primary"
                >
                    <VExpansionPanelText>
                        <span>
                            Elysia API is a backend API for my production work.
                            It is a REST API with Swagger Docs.
                        </span>
                        <div
                            class="d-flex align-center justify-item-between pt-3"
                        >
                            <VBtn
                                class="w-fit mx-3"
                                icon="mdi-github"
                                density="compact"
                                href="https://github.com/Avei20/avei-elysia"
                            />
                            <VBtn
                                class="w-fit mx-3"
                                color="primary"
                                href="https://elysia.avei.ovh/"
                            >
                                Try it!
                            </VBtn>
                        </div>
                    </VExpansionPanelText>
                </VExpansionPanel>
            </VExpansionPanels>
        </VCardItem>
        <VCardText
            >Fell free to give a feedback and hate comment here. Thanks. Your
            identity is anonymous.
        </VCardText>
        <VTextarea
            v-model="v$.message.$model"
            class="my-1 w-100 mx-2 px-3"
            variant="outlined"
            density="compact"
            label="Feedback"
            :error-messages="
                v$.message.$errors.map((e) => e.$message as string)
            "
            placeholder="Make sure your feedback is very good for my mental health and my feeling. Identity is Anonymous btw. :)"
        >
        </VTextarea>
        <VBtn class="mb-4" color="primary" @click="submitFeedback">Send</VBtn>
    </VCard>
</template>

<script setup lang="ts">
import useVuelidate from "@vuelidate/core";
import { helpers, minLength, required } from "@vuelidate/validators";

const feedbackStore = useFeedbackStore();
const appStore = useAppStore();

const form = reactive({
    message: "",
});

const rules = computed(() => {
    return {
        message: {
            required: helpers.withMessage(
                "Message is required to submit a feedback",
                required,
            ),
            minLength: helpers.withMessage(
                "Message must be at least 10 characters",
                minLength(10),
            ),
        },
    };
});

const v$ = useVuelidate(rules, feedbackStore.create);

const submitFeedback = async () => {
    const isFormCorrect = await v$.value.$validate();

    if (isFormCorrect) {
        const response = await useFetchApi("/v1/feedback", {
            method: "POST",
            body: {
                message: feedbackStore.create.message,
            },
        });

        if (response.error.value) {
            appStore.showSnackbar(response.error.value.data.message);
        }

        if (response.data.value) {
            const data = response.data.value as { message: string };
            appStore.showSnackbar(data.message);
            feedbackStore.initCreate();
            v$.value.$reset();
        }
    }
};
</script>
